config/routes.rb
Rails.application.routes.draw do

  get "/404", to: "errors#not_found", via: :all
  get "/500", to: "errors#internal_server_error", via: :all

  scope(path_names: { new: 'ny', edit: 'rediger' }) do

    devise_for :accounts, path: 'konto',
                          controllers: {
                            sessions: 'accounts/sessions',
                            registrations: 'accounts/registrations',
                          }
    root to: "home#show"
    resources :businesses, path: 'virksomhed'
    resources :developers, path: 'udviklere'
    resources :conversations, path: 'chat' do
      resources :messages
    end
    resources :businesses, path: 'virksomhed'

  end
  get '/om', to: 'about#show', as: :about
  
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: %i[ show edit update destroy ]
  before_action :authenticate_account!, only: %i[ new edit create update ]
  before_action :redirect_if_account_already_has_a_developer, only: %i[new]

  def index
    @businesses = Business.all
  end

  def show
  end

  def new
    @business = Business.new
  end

  def edit
    @business = current_account.business
    @image_required = !@business.logo.present?
  end

  def create
    @business = current_account.build_business(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to business_url(@business), notice: "Din virksomheds profil blev oprettet" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if current_account.business.update(business_params)
        format.html { redirect_to business_url(@business), notice: "Din virksomheds profil blev opdateret" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_account.business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url, notice: "Din virksomheds profil blev slettet" }
    end
  end

  private

    def redirect_if_account_already_has_a_developer
      redirect_to business_path(current_account.business) if current_account.business
    end
    
    def set_business
      @business = Business.friendly.find(params[:id])
    end

    def business_params
      params.require(:business).permit(:name, :about, :website, :logo)
    end
end

app/views/businesses/_details.html.erb
<div class='bg-white rounded shadow-sm p-3 details'>

  <div class='small-title'>LINKS</div>
  <% if @business.website %>
    <div class='py-2'>
      <div class='row'>
        <div class='col-2'>
          <%= image_tag '/images/website.png' %>
        </div>
        <div class='col-10 text-truncate'>
          <%= link_to @business.website, target: :blank do %>
            <%= @business.website.gsub('https://', '') %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/businesses/_form.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "custom/form-validator" %>
<% end %>

<%= form_with(model: @business, html: {novalidate: 'novalidate', class: 'needs-validation'}) do |f| %>
  <% if @business.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
        <% @business.errors.each do |error| %>
          <li><%= @error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1 class='pb-3'>Din virksomheds profil</h1>

  <div class='bg-white rounded p-4 shadow-sm'>
    <div class='row'>
      <div class='col-md-3'>
        <div class='fs-5 fw-semibold'>Profil</div>
        <div class='text-muted'>Denne information vil vises offentligt, så gør dig umage med, hvad du deler.</div>
      </div>
      <div class='col-md-9'>
        <div class='py-3'>
          <div class="row g-3">
            <div class="col">
              <label for='business_name' class='text-muted'>Navn</label>
              <%= f.text_field :name, class: 'form-control shadow-sm', required: true %>
              <div class="invalid-feedback">
                Skriv name
              </div>
              <div class="valid-feedback">
                👍🏼
              </div>
            </div>
            <div class="col">
              <label for='business_website' class='text-muted'>Website</label>
              <%= f.url_field :website, class: 'form-control shadow-sm' %>
              <div class="invalid-feedback">
                Skriv website
              </div>
              <div class="valid-feedback">
                👍🏼
              </div>
            </div>
          </div>
        </div>

        <div class='py-3'>
          <label for='business_about' class='text-muted'>Bio</label>
          <%= f.text_area :about, class: 'form-control shadow-sm' %>
          <div class="invalid-feedback">
            Skriv lidt om din virksomhed
          </div>
          <div class="valid-feedback">
            👍🏼
          </div>
        </div>

        <div class='py-3'>
          <div class="row g-3">
            <div class="col-6">
              <label for='business_profile_picture' class='text-muted'>Logo</label>
              <%= f.file_field :logo, class: 'form-control shadow-sm', required: @image_required %>
              <div class="invalid-feedback">
                Upload dit logo for at være mere præsentabel overfor potentielle kandidater.
              </div>
              <div class="valid-feedback">
                👍🏼
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='text-end pt-3'>
    <%= f.submit "#{'Opret profil' if action_name == 'new'}#{'Opdater profil' if action_name == 'edit'}", class: 'btn btn-primary shadow-sm' %>
  </div>

<% end %>

app/views/businesses/edit.html.erb
<%= render 'form' %>

app/views/businesses/new.html.erb
<% if @referrer == 'intro' %>

  <script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenMax.min.js"></script>

  <% content_for :head do %>
    <%= javascript_import_module_tag "custom/bg-animation" %>
  <% end %>

  <div class='bg-white rounded mt-5 shadow-sm h-75 position-relative'>
    <canvas id="canvas" class='position-absolute w-100 h-100 start-0'></canvas>
    <div style='min-height: 50vh;'>
      <div class='position-absolute w-100 h-100 p-4'>
        <div class='d-flex align-content-around flex-wrap h-100'>
          <div>
            <h1 class='fw-bold tx-primary'>OPRET VIRKSOMHEDS PROFIL</h1>
          </div>

          <div class='text-muted fs-5'>
            Bliv synlig på oversigten over danske udviklere. <br> Når du har en synlig profil, kan virksomheder kontakte dig igennem platformen med henblik på at hyre dig til et job eller en opgave.
            <br>
            Det er <strong>gratis</strong> for udviklere at bruge platformen.
          </div>

          <div>
            <%= link_to 'Ok, kom i gang!', new_business_path, class: 'btn btn-primary btn-lg shadow-sm' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'form', method: 'post', action: businesses_path %>
<% end %>

app/views/businesses/show.html.erb
<div class='business-show'>
  <div class="p-3 p-sm-5 mb-4 bg-light rounded-3 mb-4 bg-light rounded-3 shadow-sm position-relative bg-pattern-circuit">
    <div class="container-fluid py-5">
      <%= link_to 'Rediger', edit_business_path(@business), class: 'btn btn-outline-secondary bg-white position-absolute top-0 end-0 mt-3 me-3' if account_signed_in? && @current_business && @current_business == @business %>
      
      <%= image_tag business_logo(@business), class: 'rounded-circle position-absolute shadow-sm profile-picture' %>
    </div>
  </div>
  <div class='row'>
    <div class='col-md-8'>
      <div class='pt-5 p-3 p-md-5 about'>
        <div class='pb-3 pt-5'>
          <h1 class='tx-primary_brighter'><%= @business.name %></h1>
        </div>

        <hr>

        <div class='pt-3'>
          <div class='small-title'>OM</div>
          <%= @business.about %>
        </div>
      </div>
    </div>
    <div class='col-md-4'>
      <%= render 'businesses/details' %>
    </div>
  </div>
</div>