config/routes.rb
Rails.application.routes.draw do

  get "/404", to: "errors#not_found", via: :all
  get "/500", to: "errors#internal_server_error", via: :all

  scope(path_names: { new: 'ny', edit: 'rediger' }) do

    devise_for :accounts, path: 'konto',
                          controllers: {
                            sessions: 'accounts/sessions',
                            registrations: 'accounts/registrations',
                          }
    root to: "home#show"
    resources :businesses, path: 'virksomhed'
    resources :developers, path: 'udviklere'
    resources :conversations, path: 'chat' do
      resources :messages
    end
    resources :businesses, path: 'virksomhed'

  end
  get '/om', to: 'about#show', as: :about
  
end

app/models/developer.rb
class Developer < ApplicationRecord

  ##################### ASSOCIATIONS #####################
  belongs_to :account
  has_many   :projects
  has_many   :tools, through: :projects

  ##################### VALIDATIONS #####################

  validates_presence_of :first_name, :last_name, :title, :about, :city, :search_status
  validates_length_of   :title, maximum: 60,
                        with_message: I18n.t('activerecord.models.validations.max_length_title')
  validates_length_of   :first_name, :last_name,
                        maximum: 22, with_message: I18n.t('activerecord.models.validations.max_length_name')
  # validates           :first_name, :last_name, length: { maximum: 22 }
  validate              :can_not_have_custom_city

  ##################### OTHER #####################

  paginates_per 5
  extend FriendlyId
  friendly_id :name, use: :slugged
  mount_uploader :profile_picture, ProfilePictureUploader
  enum search_status: [:is_active, :unavailable, :invisible]

  def name
    (first_name.present? && last_name.present?) ? "#{first_name.capitalize} #{last_name.capitalize}" : ''
  end

  ##################### SCOPES #####################

  scope :visible, -> { where.not(search_status: 'invisible') }

  ##################### SEARCH #####################

  scope :programming_languages, -> (programming_languages) {
                                      where("'#{programming_languages}' = ANY (programming_languages)")}
  scope :city,                  -> (city) {
                                      where(city: city)}
  scope :role_levels,           -> (role_levels) {
                                      where("'#{role_levels}' = ANY (role_levels)")}
  def self.filter(filter_params)
    results = where(nil)
    filter_params.each do |key, value|
      results = results.public_send(key, value) if value.present?
    end
    results
  end
  
  private

  def can_not_have_custom_city
    unless $DEVELOPER_COUNTRY_AREAS.include?(city)
      errors.add('Developer', 'can not have a custom city')
    end
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: %i[ show update destroy ]
  before_action :authenticate_account!, only: %i[ new edit create update ]
  before_action :redirect_if_account_already_has_a_developer, only: %i[new]
  before_action :check_if_city_is_blank, only: :create

  def index
    if params[:search].present?
      Search.create_new(params[:search])
      @developers = Search.results(params[:search]).page params[:page]
      @developers_size = Search.results(params[:search]).size
    else
      @developers_size = Developer.visible.size
      @developers = Developer.visible.page params[:page]
    end
    
  end

  def show
    redirect_to developers_path, notice: t('developers.redirects.invisible') if @developer.invisible?
  end

  def new
    @developer = Developer.new
  end

  def edit
    @developer = current_account.developer
    @image_required = !@developer.profile_picture.present?
  end

  def create
    @developer = current_account.build_developer(developer_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to developer_url(@developer), notice: "Din udvikler profil blev oprettet" }
      else
        p @developer.errors.full_messages
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if current_account.developer.update(developer_params)
        format.html { redirect_to developer_url(@developer), notice: "Din udvikler profil blev opdateret" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_account.developer.destroy

    respond_to do |format|
      format.html { redirect_to developers_url, notice: "Din udvikler profil blev slettet" }
    end
  end

  private

    def check_if_city_is_blank
      if params[:developer][:city] == 'Vælg by'
        redirect_to new_developer_path, notice: 'Hov 😮 venligst vælg dit område'
      end
    end

    def redirect_if_account_already_has_a_developer
      redirect_to developer_path(current_account.developer) if current_account.developer
    end

    def set_developer
      @developer = Developer.friendly.find(params[:id])
    end

    def developer_params
      params.require(:developer).permit(
                                        :profile_picture,
                                        :title,
                                        :about,
                                        :city,
                                        :first_name,
                                        :last_name,
                                        :website,
                                        :github,
                                        :search_status,
                                        :allow_notifications,
                                        role_levels: [],
                                        programming_languages: [],
                                        role_types: []
                                      )
    end
end

app/views/developers/_card_sm.html.erb
<div class="card border-0 shadow-sm position-relative overflow-hidden rounded-4">
  <div class="card-body">
    <%= link_to developer_path(developer) do %>
      
      
      <div class='float-sm-end tx-13 status'>
        <div class='<%= search_status_color_class(developer, developer.search_status) %>'>
          <i class="fa-solid fa-circle-check"></i> <%= t "developers.search_statuses.#{developer.search_status}" %>
        </div>
        <div class='text-secondary'>
          <i class="fa-solid fa-location-dot"></i>
          <%= developer.city %>
        </div>
      </div>

      
      <div class='d-flex'>
        <div class="flex-shrink-0">
          <%= image_tag developer_pic(developer, 40), class: 'rounded-4 shadow-sm' %>
        </div>
        <div class="flex-grow-1 ms-3">
          <h5 class="card-title tx-primary_brighter two-lines"><%= developer.title %></h5>
          <div class='nowrap text-truncate'><%= developer.name %></div>
          <div>
            <small class='tx-primary'>
              <%= developer.role_levels.join(', ').titleize %>
            </small>
          </div>
          <div class='pt-1'>
            <% developer.programming_languages.max(8).each do |lang| %>
              <%= link_to developers_path(language: lang), class: 'd-inline-block' do %>
                <small class='tx-complementary_brighter bg-complementary_ultra_brighter rounded px-1 me-1 tag'><span class='opacity-50'>#</span> <%= lang %></small>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <p class="card-text">
        <div class='p-1 rounded'>
        </div>
      </p>
    <% end %>
  </div>
</div>

app/views/developers/_details.html.erb
<div class='bg-white rounded shadow-sm p-3 details'>

  <div class='py-2'>
    <div class='small-title mb-2'>SPROG/FRAMEWORKS</div>
    <% @developer.programming_languages.each do |lang| %>
      <div class='bg-primary text-white rounded p-1 px-2 d-inline-block me-1 mb-1 shadow-sm'><%= lang %></div>
    <% end %>
  </div>
  <hr>
  <div class='py-2'>
    <div class='small-title mb-2'>ROLLER</div>
    <% $DEVELOPER_ROLE_TYPES.each do |role| %>
      <div class='pb-2 <%= role_types_color_class(@developer, role) %>'>
        <div class='pe-2 d-inline'>
          <i class="<%= fa_circle_class_for_role_types(@developer, role) %> fa-circle-check"></i>
        </div>
        <%= t "developers.role_types.#{role}" %>
      </div>
    <% end %>
  </div>
  <hr>
  <div class='py-2'>
    <div class='small-title mb-2'>LEVEL</div>
    <% $DEVELOPER_ROLE_LEVELS.each do |level| %>
      <div class='pb-2 <%= role_level_color_class(@developer, level) %>'>
        <div class='pe-2 d-inline'>
          <i class="<%= fa_circle_class_for_role_level(@developer, level) %> fa-circle-check"></i>
        </div>
        <%= t "developers.role_levels.#{level}" %>
      </div>
    <% end %>
  </div>
  <hr>
  <div class='py-2'>
    <div class='small-title mb-2'>SØGESTATUS</div>
    <% $DEVELOPER_SEARCH_STATUSES.first(2).each do |status| %>
      <div class='pb-2 <%= search_status_color_class(@developer, status) %>'>
        <div class='pe-2 d-inline'>
          <i class="<%= fa_circle_class_for_search_status(@developer, status) %> fa-circle-check"></i>
        </div>
        <%= t "developers.search_statuses.#{status}" %>
      </div>
    <% end %>
  </div>
  <hr>
  <div class='py-2'>
    <div class='small-title'>OMRÅDE</div>
    <%= @developer.city %>
  </div>
  <% if @developer.website || @developer.github %>
    <hr>
    <div class='small-title'>LINKS</div>
    <% if @developer.website %>
      <div class='py-2'>
        <div class='row'>
          <div class='col-2'>
            <%= image_tag '/images/website.png' %>
          </div>
          <div class='col-10 text-truncate'>
            <%= link_to @developer.website, target: :blank do %>
              <%= @developer.website.gsub('https://', '') %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <% if @developer.github %>
      <div class='py-2'>
        <div class='row'>
          <div class='col-2'>
            <%= image_tag '/images/github.png' %>
          </div>
          <div class='col-10 text-truncate'>
            <%= link_to @developer.github, target: :blank do %>
              <%= @developer.github.gsub('https://', '') %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/developers/_developer.html.erb
<div id="<%= dom_id developer %>">
</div>

app/views/developers/_form.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "custom/form-validator" %>
  <%= javascript_import_module_tag "custom/select2" %>
<% end %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<%= form_with(model: @developer, html: {novalidate: 'novalidate', class: 'needs-validation'}) do |f| %>
  <% if @developer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
        <% @developer.errors.each do |error| %>
          <li><%= @error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1 class='pb-3'>Din udvikler profil</h1>

  <div class='bg-white rounded p-4 shadow-sm'>
    <div class='row'>
      <div class='col-md-3'>
        <div class='fs-5 fw-semibold'>Profil</div>
        <div class='text-muted'>Denne information vil vises offentligt, så gør dig umage med, hvad du deler.</div>
      </div>
      <div class='col-md-9'>
        <div class='py-3'>
          <div class="row g-3">
            <div class="col">
              <label for='developer_first_name' class='text-muted'>Fornavn</label>
              <%= f.text_field :first_name, class: 'form-control shadow-sm', max: 22, required: true %>
              <div class="invalid-feedback">
                Skriv fornavn
              </div>
              <div class="valid-feedback">
                👍🏼
              </div>
            </div>
            <div class="col">
              <label for='developer_last_name' class='text-muted'>Efternavn</label>
              <%= f.text_field :last_name, class: 'form-control shadow-sm', max: 22, required: true %>
              <div class="invalid-feedback">
                Skriv efternavn
              </div>
              <div class="valid-feedback">
                👍🏼
              </div>
            </div>
          </div>
        </div>

        <div class='py-3'>
          <div class="row g-3">
            <div class="col">
              <label for='developer_title' class='text-muted'>Titel</label>
              <%= f.text_field :title, class: 'form-control shadow-sm', max: 42, required: true %>
              <div class="invalid-feedback">
                Skriv titel
              </div>
              <div class="valid-feedback">
                👍🏼
              </div>
            </div>
            <div class="col developer_city_wrapper">
              <label for="developer_city" class="text-muted">Område</label>
              <select name='developer[city]' id="developer_city" class='form-control select2' required='required'>
                <option selected='selected'>Vælg by</option>
                <%= $DEVELOPER_COUNTRY_AREAS.each do |area| %>
                  <option value='<%= area %>' <%= 'selected' if area == @developer.city %>><%= area %></option>
                <% end %>
              </select>
              <div class="invalid-feedback">
                Vælg dit område
              </div>
              <div class="valid-feedback">
                👍🏼
              </div>
            </div>
          </div>
        </div>

        <div class='py-3'>
          <label for='developer_about' class='text-muted'>Bio</label>
          <%= f.text_area :about, class: 'form-control shadow-sm', required: true %>
          <div class="invalid-feedback">
            Skriv lidt om dig selv
          </div>
          <div class="valid-feedback">
            👍🏼
          </div>
        </div>

        <div class='py-3'>
          <div class="row g-3">
            <div class="col-6">
              <label for='developer_profile_picture' class='text-muted'>Profil billede</label>
              <%= f.file_field :profile_picture, class: 'form-control shadow-sm', required: @image_required %>
              <div class="invalid-feedback">
                Velg et profil billede. Dette øger dine chancer for at blive kontaktet.
              </div>
              <div class="valid-feedback">
                👍🏼
              </div>
            </div>
            <div class='col-6 developer_programming_languages_wrapper'>
              <label for="developer_programming_languages" class="text-muted nowrap">Sprog/frameworks</label>
              <select name='developer[programming_languages][]' multiple='multiple' id="developer_programming_languages" class='form-control select2 w-100' required>
                <%= $DEVELOPER_LANGUAGES.sort.each do |language| %>
                  <option value='<%= language %>' <%= 'selected' if @developer.programming_languages && @developer.programming_languages.include?(language) %>><%= language %></option>
                <% end %>
              </select>
              <div class="invalid-feedback">
                Vælg sprog/frameworks
              </div>
              <div class="valid-feedback">
                👍🏼
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class='bg-white rounded p-4 mt-5 shadow-sm'>
    <div class='row'>
      <div class='col-md-3'>
        <div class='fs-5 fw-semibold'>Arbejds præferencer</div>
        <div class='text-muted'>Hvilken slags arbejde leder du efter?</div>
      </div>
      <div class='col-md-9'>
        <div class='py-3'>
          <div class='fs-5 pb-3'>Søge status</div>
          <% $DEVELOPER_SEARCH_STATUSES.each do |status| %>
            <div class="form-check py-2">
              <input class="form-check-input" type="radio" name="developer[search_status]" id="developer_search_status_<%= status %>" value='<%= status %>' <%= 'checked' if @developer.search_status == status %>>
              <label class="form-check-label pointer" for="developer_search_status_<%= status %>">
                <%= t "developers.search_statuses.#{status}" %>
              </label>
            </div>
          <% end %>
        </div>

        <div class='py-3 role-types'>
          <div class='fs-5 pb-3'>Hvilken type(r) søger du?</div>
          <% $DEVELOPER_ROLE_TYPES.each do |role| %>
            <div class="form-check py-2 ps-5">
              <input class="form-check-input" name='developer[role_types][]' type="checkbox" value="<%= role %>" id="developer_role_types_<%= role %>" <%= 'checked' if @developer.role_types && @developer.role_types.include?("#{role}") %>>
              <label class="form-check-label pointer" for="developer_role_types_<%= role %>">
                <%= t "developers.role_types.#{role}" %>
              </label>
            </div>
          <% end %>
        </div>

        <div class='py-3 role-types'>
          <div class='fs-5 pb-3'>Hvilket level søger du?</div>
          <% $DEVELOPER_ROLE_LEVELS.each do |role| %>
            <div class="form-check py-2 ps-5">
              <input class="form-check-input" name='developer[role_levels][]' type="checkbox" value="<%= role %>" id="developer_role_levels_<%= role %>" <%= 'checked' if @developer.role_levels && @developer.role_levels.include?("#{role}") %>>
              <label class="form-check-label pointer" for="developer_role_levels_<%= role %>">
                <%= t "developers.role_levels.#{role}" %>
              </label>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class='bg-white rounded p-4 mt-5 shadow-sm'>
    <div class='row'>
      <div class='col-md-3'>
        <div class='fs-5 fw-semibold'>Online tilstedeværelse</div>
        <div class='text-muted'>Hvor kan man se og lære mere om dig?</div>
      </div>
      <div class='col-md-9'>
        <div class='py-3'>
          <div class="row g-3">
            <div class="col">
              <label for='developer_website' class='text-muted'>Website</label>
              <%= f.url_field :website, class: 'form-control shadow-sm' %>
            </div>
            <div class="col">
              <label for='developer_github' class='text-muted'>Github</label>
              <%= f.url_field :github, class: 'form-control shadow-sm' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='bg-white rounded p-4 mt-5 shadow-sm'>
    <div class='row'>
      <div class='col-md-3'>
        <div class='fs-5 fw-semibold'>Email notifikationer</div>
      </div>
      <div class='col-md-9'>
        <div class='py-3'>
          <div class="form-check py-2">
            <input class="form-check-input" name='developer[allow_notifications]' type="checkbox" value="true" id="developer_allow_notifications" <%= 'checked' if current_account.developer && current_account.developer.allow_notifications || !current_account.developer %>>
            <label class="form-check-label pointer" for="developer_allow_notifications">
              Tillad email notifikationer
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='text-end pt-3'>
    <%= f.submit "#{'Opret profil' if action_name == 'new'}#{'Opdater profil' if action_name == 'edit'}", class: 'btn btn-primary shadow-sm' %>
  </div>

<% end %>

app/views/developers/_index.html.erb
<% if @developers.any? %>
  <div class='text-end py-1'>
    <%= @developers_size %> <%= t 'developers.index.search.results' %>
  </div>
  <% @developers.each do |developer| %>
    <div class='pb-3'>
    <%# <div class='col-md-6 col-sm-12 py-2'> %>
      <%= render 'card_sm', developer: developer %>
    </div>
  <% end %>
  <%= paginate @developers %>
<% else %>
  <div class='pt-5 fs-5 mt-5 mt-sm-0'>
    <%= t 'developers.index.search.no_results' %>
  </div>
<% end %>

app/views/developers/_search.html.erb
<button class='btn btn-sm bg-light show-on-mobile w-100 shadow-sm border-light p-2 mb-3' id='viev_search'><i class="fa-solid fa-magnifying-glass"></i> <span>Filtrér</span></button>

<div class='bg-white rounded shadow-sm p-3'>
  
  <%= form_tag developers_path, id: 'search', class: 'hide-on-mobile', method: 'get', remote: true do |f| %>

    <div class='row'>
      <div class='col-12 col-sm-12 py-md-2'>
        <%= render 'developers/search/languages' %>
      </div>
      <div class='col-6 col-sm-12 py-md-2'>
        <%= render 'developers/search/role_levels' %>
      </div>
      <div class='col-6 col-sm-12 py-md-2'>
        <%= render 'developers/search/cities' %>
      </div>
    </div>
  <% end %>

</div>

<script>

  $(document).on('click', '#viev_search', function() {
    $('#search').toggleClass('hide-on-mobile');
    if($('#search').hasClass('hide-on-mobile')) {
      $(this).find('span').text('Filtrér'); 
    } else {
      $(this).find('span').text('Skjul filtrering'); 
    }
  })

</script>

app/views/developers/index.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "custom/search" %>
<% end %>


<div class='row'>
  <div class='col-sm-3'>
    <%= render 'search' %>
  </div>
  <div class='col-sm-9'>
    <div id='results'>
      <%= render 'index' %>
    </div>
  </div>
</div>

app/views/developers/index.js.erb
$('#results').html('<%= j render 'developers/index' %>');

AOS.refresh();

<% if @referrer == 'scroll' %>

  $('#results').append('<%= j render @expeditions_paginated %>');

  $('.spinner-border').closest('center').remove();

  <% if @expeditions_paginated.next_page %>

    $('.pagination').replaceWith('<%= j will_paginate(@expeditions_paginated) %>');
  <% else %>

    $('.pagination').remove();

  <% end %>

  <% sleep 1 %>

<% end %>

app/views/developers/new.html.erb
<% if @referrer == 'intro' %>

  <script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenMax.min.js"></script>

  <% content_for :head do %>
    <%= javascript_import_module_tag "custom/bg-animation" %>
  <% end %>

  <div class='bg-white rounded mt-5 shadow-sm h-75 position-relative'>
    <canvas id="canvas" class='position-absolute w-100 h-100 start-0'></canvas>
    <div style='min-height: 50vh;'>
      <div class='position-absolute w-100 h-100 p-4'>
        <div class='d-flex align-content-around flex-wrap h-100'>
          <div>
            <h1 class='fw-bold tx-primary'>ORPET PROFIL</h1>
          </div>

          <div class='text-muted fs-5'>
            Bliv synlig på oversigten over danske udviklere. <br> Når du har en synlig profil, kan virksomheder kontakte dig igennem platformen med henblik på at hyre dig til et job eller en opgave.
            <br>
            Det er <strong>gratis</strong> for udviklere at bruge platformen.
          </div>

          <div>
            <%= link_to 'Ok, cool!', new_developer_path, class: 'btn btn-primary btn-lg shadow-sm' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'form', method: 'post', action: '/udviklere' %>
<% end %>

app/views/developers/show.html.erb
<div class='developer-show'>
  <div class="p-3 p-sm-5 mb-4 bg-light rounded-3 mb-4 bg-light rounded-3 shadow-sm position-relative bg-pattern-circuit">
    <div class="container-fluid py-5">
      <%= link_to 'Rediger', edit_developer_path(@developer), class: 'btn btn-outline-secondary bg-white position-absolute top-0 end-0 mt-3 me-3' if account_signed_in? && @current_developer && @current_developer == @developer %>
      <%= image_tag developer_pic(@developer, 200), class: 'rounded-circle position-absolute shadow-sm profile-picture' %>
    </div>
  </div>
  <div class='row'>
    <div class='col-md-8'>
      <div class='pt-5 p-3 p-md-5 about'>
        <div class='pb-3'>
          <h1 class='tx-primary_brighter'><%= @developer.title %></h1>
          <h2 class='text-muted fw-bold'><%= @developer.name %></h2>
        </div>

        <%= new_message_path(current_account, @developer) if account_signed_in? && can_send_message?(@developer) %>

        <hr>

        <div class='pt-3'>
          <div class='small-title'>OM</div>
          <%= @developer.about %>
        </div>
      </div>
    </div>
    <div class='col-md-4'>
      <%= render 'developers/details' %>
    </div>
  </div>
</div>