config/routes.rb
Rails.application.routes.draw do

  get "/404", to: "errors#not_found", via: :all
  get "/500", to: "errors#internal_server_error", via: :all

  scope(path_names: { new: 'ny', edit: 'rediger' }) do

    devise_for :accounts, path: 'konto',
                          controllers: {
                            sessions: 'accounts/sessions',
                            registrations: 'accounts/registrations',
                          }
    root to: "home#show"
    resources :businesses, path: 'virksomhed'
    resources :developers, path: 'udviklere'
    resources :conversations, path: 'chat' do
      resources :messages
    end
    resources :businesses, path: 'virksomhed'

  end
  get '/om', to: 'about#show', as: :about
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @developers = Developer.visible.order(created_at: :desc).limit(6)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_icons.html.erb
<div class='row lang-icons text-center'>
  <div class='col-md-2 col-6 p-3'>
    <div class='py-4 tx-primary rounded shadow-sm'>
      <i class="fa-brands fa-vuejs"></i>
    </div>
  </div>
  <div class='col-md-2 col-6 p-3'>
    <div class='py-4 tx-primary rounded shadow-sm'>
      <i class="fa-brands fa-react"></i>
    </div>
  </div>
  <div class='col-md-2 col-6 p-3'>
    <div class='py-4 tx-primary rounded shadow-sm'>
      <i class="fa-brands fa-css3-alt"></i>
    </div>
  </div>
  <div class='col-md-2 col-6 p-3'>
    <div class='py-4 tx-primary rounded shadow-sm'>
      <i class="fa-brands fa-python"></i>
    </div>
  </div>
  <div class='col-md-2 col-6 p-3'>
    <div class='py-4 tx-primary rounded shadow-sm'>
      <i class="fa-brands fa-js"></i>
    </div>
  </div>
  <div class='col-md-2 col-6 p-3'>
    <div class='py-4 tx-primary rounded shadow-sm'>
      <i class="fa-brands fa-php"></i>
    </div>
  </div>
  <div class='col-md-2 col-6 p-3'>
    <div class='py-4 tx-primary rounded shadow-sm'>
      <i class="fa-brands fa-java"></i>
    </div>
  </div>
  <div class='col-md-2 col-6 p-3'>
    <div class='py-4 tx-primary rounded shadow-sm'>
      <i class="fa-brands fa-golang"></i>
    </div>
  </div>
  <div class='col-md-2 col-6 p-3'>
    <div class='py-4 tx-primary rounded shadow-sm'>
      <i class="fa-brands fa-rust"></i>
    </div>
  </div>
  <div class='col-md-2 col-6 p-3'>
    <div class='py-4 tx-primary rounded shadow-sm'>
      <i class="fa-brands fa-swift"></i>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<div id='home'>

  <div class='px-md-5'>
    <%= render 'components/header' %>

    <%= render 'icons' %>
  </div>

  <h2>Nye udviklere</h2>


  <div class='row'>
    <% @developers.each do |developer| %>
      <div class='col-md-6 py-3'>
        <%= render 'developers/card_sm', developer: developer %>
      </div>
    <% end %>
  </div>

  <div class='text-center pt-4'>
    <%= link_to 'Se flere...', developers_path, class: 'btn btn-lg bg-white shadow-sm py-3 px-5 fs-3' %>
  </div>
</div>